# Generated by Django 4.0.4 on 2022-05-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersysapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrator',
            new_name='HOD',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Staff'), ('3', 'Student')], default=1, max_length=10),
        ),
    ]
