# Generated by Django 4.0.4 on 2022-05-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mersysapp', '0003_rename_hod_adminhod'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default=None, max_length=255)),
                ('group_leader_name', models.CharField(default=None, max_length=255)),
                ('group_leader_phone', models.CharField(default=None, max_length=255)),
                ('partner_name', models.CharField(default=None, max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.county')),
            ],
        ),
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('household_name', models.CharField(max_length=255)),
                ('household_size', models.IntegerField()),
                ('gps_coordinates', models.DecimalField(decimal_places=16, max_digits=22)),
                ('participant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('group_membership', models.CharField(blank=True, choices=[('Agricultural/Livestock,Fisheries Producer’s Group', 'Agricultural/Livestock/Fisheries Producer’s Group (including marketing groups)'), ('Water Users’ Group', 'Water Users’ Group'), ('Credit or Microfinance Group', 'Credit or Microfinance Group (including SACCOs/merry-go-rounds/ VSLAs)'), ('Other', 'Other [Women’s/Men’s] Group (only if it does not fit into one of the other categories)')], default=None, max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('individual_type', models.CharField(choices=[('Parents/Caregivers', 'Parents/Caregivers'), ('Household Members', 'Household Members'), ('People in Government', 'People in Government'), ('People in USG Private Sector Assisted Firms', 'People in USG Private Sector Assisted Firms'), ('People in Civil Society', 'People in Civil Society'), ('Laborers', 'Laborers'), ('Producers (Smallholder)', 'Producers (Smallholder)'), ('Producer (Non-Smallholder)', 'Producer (Non-Smallholder)'), ('Producer (Aquaculture)', 'Producer (Aquaculture)'), ('Producer (Size Disaggregate Not Available)', 'Producer (Size Sisaggregate not Available)'), ('Individual Type (Not Applicable)', 'Individual Type Not Applicable'), ('Disaggregate Not Available', 'Disaggregate Not Available')], default=None, max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('livelihood_status', models.CharField(choices=[('Pastoralist', 'Pastoralist'), ('Agro-Pastoralist', 'Agro-Pastoralist'), ('Fishermen', 'Fishermen'), ('Trader', 'Trader'), ('Others', 'Others (Specify)')], default=None, max_length=255)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.county')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('relationship_HH', models.CharField(choices=[('Husband', 'Husband'), ('Wife', 'Wife'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Son/Daughter-in-Law', 'Son/Daughter-in-Law'), ('Grandchild', 'Grandchild'), ('Other Relative', 'Other Relative')], default=None, max_length=30)),
                ('dob', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30)),
                ('group_membership', models.CharField(blank=True, choices=[('Agricultural/Livestock,Fisheries Producer’s Group', 'Agricultural/Livestock/Fisheries Producer’s Group (including marketing groups)'), ('Water Users’ Group', 'Water Users’ Group'), ('Credit or Microfinance Group', 'Credit or Microfinance Group (including SACCOs/merry-go-rounds/ VSLAs)'), ('Other', 'Other [Women’s/Men’s] Group (only if it does not fit into one of the other categories)')], default=None, max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('individual_type', models.CharField(choices=[('Parents/Caregivers', 'Parents/Caregivers'), ('Household Members', 'Household Members'), ('People in Government', 'People in Government'), ('People in USG Private Sector Assisted Firms', 'People in USG Private Sector Assisted Firms'), ('People in Civil Society', 'People in Civil Society'), ('Laborers', 'Laborers'), ('Producers (Smallholder)', 'Producers (Smallholder)'), ('Producer (Non-Smallholder)', 'Producer (Non-Smallholder)'), ('Producer (Aquaculture)', 'Producer (Aquaculture)'), ('Producer (Size Disaggregate Not Available)', 'Producer (Size Sisaggregate not Available)'), ('Individual Type (Not Applicable)', 'Individual Type Not Applicable'), ('Disaggregate Not Available', 'Disaggregate Not Available')], default=None, max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('livelihood_status', models.CharField(choices=[('Pastoralist', 'Pastoralist'), ('Agro-Pastoralist', 'Agro-Pastoralist'), ('Fishermen', 'Fishermen'), ('Trader', 'Trader'), ('Others', 'Others (Specify)')], default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_County',
            fields=[
                ('sub_county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_county_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.county')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vllage_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.county')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.sub_county')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.county')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.sub_county')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='feedbackstaffs',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='notificationstaffs',
            name='stafff_id',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Staff')], default=1, max_length=10),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='FeedBackStaffs',
        ),
        migrations.DeleteModel(
            name='FeedBackStudent',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
        migrations.DeleteModel(
            name='NotificationStaffs',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.AddField(
            model_name='village',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.ward'),
        ),
        migrations.AddField(
            model_name='household',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.sub_county'),
        ),
        migrations.AddField(
            model_name='household',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.village'),
        ),
        migrations.AddField(
            model_name='household',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.ward'),
        ),
        migrations.AddField(
            model_name='groups',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.sub_county'),
        ),
        migrations.AddField(
            model_name='groups',
            name='vllage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.village'),
        ),
        migrations.AddField(
            model_name='groups',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersysapp.ward'),
        ),
    ]
